/**
 * Boot survival — the answer to "I left it running and woke up to eight dead hours".
 *
 * Two independent causes killed that night: a stale STOP flag (the supervisor's problem)
 * and NOTHING supervising the processes — `temporal server start-dev`, the worker and the
 * dashboard were bare background children of a shell. A crash, a reboot, or closing that
 * shell was permanent death, because no OS-level thing ever tried to start them again.
 *
 * This module registers that OS-level thing. It does not supervise anything itself: it
 * makes the platform run `spicyspec-runner supervise --once` at boot/logon AND every few
 * minutes forever. One sweep is cheap and idempotent, so "every 3 minutes" is the whole
 * recovery policy — the worst outage is one interval long.
 *
 * Every vector is built by a pure function and executed separately, so the argv can be
 * asserted in tests without touching the real Task Scheduler / systemd / launchd.
 */
import { execFile } from 'node:child_process';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { promisify } from 'node:util';

const run = promisify(execFile);

export type AutostartKind = 'schtasks' | 'systemd-user' | 'launchd';

/** One argv, never a shell string — a path with spaces must not become two arguments. */
export interface CommandVector {
  readonly bin: string;
  readonly args: readonly string[];
  /** what this call is for; printed verbatim when the tool is missing so a human can run it */
  readonly label: string;
  /** a teardown that legitimately fails when nothing was installed yet */
  readonly optional?: boolean;
}

export interface PlannedFile {
  readonly path: string;
  readonly content: string;
  readonly executable?: boolean;
}

export interface AutostartPlan {
  readonly kind: AutostartKind;
  /** scheduled-task / unit / label name — stable, so re-running updates instead of duplicating */
  readonly unitName: string;
  /** the executable the install vectors need; absent => write the files, print the commands */
  readonly requiresTool: string;
  /** created up front: appending to a log inside a missing directory fails silently at 3am */
  readonly logDir: string;
  readonly files: readonly PlannedFile[];
  readonly install: readonly CommandVector[];
  readonly uninstall: readonly CommandVector[];
  /** lines the founder can paste to see for themselves that it is registered */
  readonly verify: readonly string[];
  readonly notes: readonly string[];
  readonly needsElevation: boolean;
}

export interface AutostartRequest {
  readonly projectName: string;
  /** absolute — a scheduled task has no cwd worth trusting */
  readonly configPath: string;
  /** absolute path to the runner's bin.js */
  readonly cliPath: string;
  /** absolute path to the node binary that will run it */
  readonly nodePath: string;
  /** how often the sweep repeats; also the worst-case outage length */
  readonly intervalMinutes: number;
  /** <repoCwd>/.spicyspec — launcher script and logs live here */
  readonly stateDir: string;
  /**
   * Windows only: register the task to run whether or not the user is logged on. Costs an
   * elevated shell AND a SYSTEM profile, which is usually the wrong trade here — see the
   * note the planner attaches.
   */
  readonly whetherLoggedOn?: boolean;
  readonly platform?: NodeJS.Platform;
  readonly homeDir: string;
  readonly uid?: number;
}

/**
 * Task/unit names are matched literally on uninstall, so the sanitizer must be stable, and
 * must strip the characters schtasks treats as path separators (a backslash nests a task in
 * a folder — `Spicyspec-my\proj` would install somewhere the delete never looks).
 */
export function autostartName(projectName: string): string {
  const safe = projectName
    .replace(/[^A-Za-z0-9._-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return `Spicyspec-${safe || 'project'}`;
}

function slug(projectName: string): string {
  return autostartName(projectName).slice('Spicyspec-'.length).toLowerCase();
}

export function supervisorLogDir(stateDir: string): string {
  return join(stateDir, 'logs');
}

/**
 * The scheduled task points at this script, not at node directly: schtasks truncates /TR
 * past ~261 characters, and node path + cli path + config path blows that budget on any
 * real Windows layout. The indirection also gives the sweep somewhere to append output.
 */
export function windowsLauncherScript(req: AutostartRequest): string {
  const logDir = supervisorLogDir(req.stateDir);
  return [
    '@echo off',
    // The supervisor writes UTF-8 (em-dashes in every line); cmd's default OEM codepage
    // renders those as mojibake in the very log a founder reads at 3am to see what healed.
    'chcp 65001 >nul',
    'REM Generated by `spicyspec-runner install-autostart` — regenerate, do not hand-edit.',
    'REM One supervision sweep. The scheduled task runs it at logon and on an interval;',
    'REM the sweep is what restarts Temporal, the worker, the dashboard and the rotation.',
    `if not exist "${logDir}" mkdir "${logDir}"`,
    // NO shell redirect: the supervisor appends to the log itself. cmd's `>>` opens the file
    // for the whole process, so any other holder — an overlapping sweep, a tail — made the
    // launcher exit 1 before node started, running no checks and writing nothing.
    // --interval carries the SCHEDULER's cadence into the heartbeat: the room marks the
    // supervisor missing after three missed beats, and a sweep that declared the config's
    // 60s while the task fired every 3 minutes made the header read UNSUPERVISED half the
    // time with nothing actually wrong.
    `"${req.nodePath}" "${req.cliPath}" supervise --once --interval ${req.intervalMinutes * 60} --config "${req.configPath}"`,
    '',
  ].join('\r\n');
}

function windowsPlan(req: AutostartRequest): AutostartPlan {
  const unitName = autostartName(req.projectName);
  const bootTask = `${unitName}-boot`;
  const launcher = join(req.stateDir, 'autostart', 'supervise.cmd');
  const elevated = req.whetherLoggedOn === true;
  // `/RU SYSTEM` is the only non-interactive principal schtasks can register without a
  // stored password, and it implies elevation.
  const principal = elevated ? ['/RU', 'SYSTEM', '/RL', 'HIGHEST'] : [];
  // `/F` is the whole idempotency story: it overwrites an existing task of the same name
  // instead of erroring, so re-running install-autostart updates rather than duplicating.
  const create = (name: string, schedule: readonly string[], label: string): CommandVector => ({
    bin: 'schtasks',
    args: ['/Create', '/TN', name, '/TR', `"${launcher}"`, ...schedule, ...principal, '/F'],
    label,
  });

  const notes = [
    `the sweep runs every ${req.intervalMinutes} minute(s) — that is also the worst-case outage`,
    `output is appended to ${join(supervisorLogDir(req.stateDir), 'supervisor.log')}`,
  ];
  if (elevated) {
    notes.push(
      'registered as SYSTEM: this needs an ELEVATED shell, and SYSTEM has no user profile —',
      'ambient AI-account logins live in YOUR profile, so the workers it starts may fail to',
      'authenticate. Prefer the default (drop --whether-logged-on) unless you know otherwise.',
    );
  } else {
    notes.push(
      'not elevated, and it does not need to be: the task runs as you, at logon and on the',
      'interval, and keeps your profile (where the AI-account logins live). It cannot fire',
      'while nobody is logged on — for that, re-run in an ELEVATED shell with',
      '--whether-logged-on (registers as SYSTEM; read the caveat it prints).',
    );
  }

  return {
    kind: 'schtasks',
    unitName,
    requiresTool: 'schtasks',
    logDir: supervisorLogDir(req.stateDir),
    files: [{ path: launcher, content: windowsLauncherScript(req) }],
    install: [
      create(
        unitName,
        ['/SC', 'MINUTE', '/MO', String(req.intervalMinutes)],
        `repeating sweep every ${req.intervalMinutes}m`,
      ),
      // ONSTART fires before any session exists, so it is only meaningful for the SYSTEM
      // principal; as a normal user the equivalent boot trigger is ONLOGON.
      create(bootTask, ['/SC', elevated ? 'ONSTART' : 'ONLOGON'], elevated ? 'sweep at boot' : 'sweep at logon'),
    ],
    uninstall: [
      { bin: 'schtasks', args: ['/Delete', '/TN', unitName, '/F'], label: 'remove the repeating sweep', optional: true },
      { bin: 'schtasks', args: ['/Delete', '/TN', bootTask, '/F'], label: 'remove the boot sweep', optional: true },
    ],
    verify: [`schtasks /Query /TN ${unitName} /V /FO LIST`, `schtasks /Query /TN ${bootTask} /V /FO LIST`],
    notes,
    needsElevation: elevated,
  };
}

export function systemdServiceUnit(req: AutostartRequest): string {
  const log = join(supervisorLogDir(req.stateDir), 'supervisor.log');
  return [
    '[Unit]',
    `Description=Spicyspec supervision sweep (${req.projectName})`,
    '',
    '[Service]',
    'Type=oneshot',
    `ExecStart="${req.nodePath}" "${req.cliPath}" supervise --once --interval ${req.intervalMinutes * 60} --config "${req.configPath}"`,
    `StandardOutput=append:${log}`,
    `StandardError=append:${log}`,
    '',
  ].join('\n');
}

export function systemdTimerUnit(req: AutostartRequest): string {
  return [
    '[Unit]',
    `Description=Spicyspec supervision sweep every ${req.intervalMinutes}min (${req.projectName})`,
    '',
    '[Timer]',
    'OnBootSec=1min',
    `OnUnitActiveSec=${req.intervalMinutes}min`,
    // A machine asleep past a tick must sweep on wake, not wait out the interval.
    'Persistent=true',
    `Unit=spicyspec-${slug(req.projectName)}.service`,
    '',
    '[Install]',
    'WantedBy=timers.target',
    '',
  ].join('\n');
}

function systemdPlan(req: AutostartRequest): AutostartPlan {
  const name = `spicyspec-${slug(req.projectName)}`;
  const dir = join(req.homeDir, '.config', 'systemd', 'user');
  return {
    kind: 'systemd-user',
    unitName: `${name}.timer`,
    requiresTool: 'systemctl',
    logDir: supervisorLogDir(req.stateDir),
    files: [
      { path: join(dir, `${name}.service`), content: systemdServiceUnit(req) },
      { path: join(dir, `${name}.timer`), content: systemdTimerUnit(req) },
    ],
    // Writing a unit twice is already idempotent; daemon-reload + `enable --now` makes the
    // second run an update rather than a duplicate.
    install: [
      { bin: 'systemctl', args: ['--user', 'daemon-reload'], label: 're-read the unit files' },
      { bin: 'systemctl', args: ['--user', 'enable', '--now', `${name}.timer`], label: 'enable and start the timer' },
    ],
    uninstall: [
      {
        bin: 'systemctl',
        args: ['--user', 'disable', '--now', `${name}.timer`],
        label: 'stop and disable the timer',
        optional: true,
      },
      { bin: 'systemctl', args: ['--user', 'daemon-reload'], label: 're-read the unit files' },
    ],
    verify: [`systemctl --user status ${name}.timer`, `journalctl --user -u ${name}.service -n 50`],
    notes: [
      'a USER timer, so no root and no sudo',
      'run once: loginctl enable-linger $USER — without lingering the timer stops when you log out',
      `output is appended to ${join(supervisorLogDir(req.stateDir), 'supervisor.log')}`,
    ],
    needsElevation: false,
  };
}

export function launchdPlist(req: AutostartRequest): string {
  const log = join(supervisorLogDir(req.stateDir), 'supervisor.log');
  const label = `com.spicyspec.${slug(req.projectName)}`;
  const argv = [req.nodePath, req.cliPath, 'supervise', '--once', '--config', req.configPath];
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<plist version="1.0">',
    '<dict>',
    `  <key>Label</key><string>${label}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    ...argv.map((a) => `    <string>${esc(a)}</string>`),
    '  </array>',
    '  <key>RunAtLoad</key><true/>',
    `  <key>StartInterval</key><integer>${req.intervalMinutes * 60}</integer>`,
    `  <key>StandardOutPath</key><string>${esc(log)}</string>`,
    `  <key>StandardErrorPath</key><string>${esc(log)}</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

function launchdPlan(req: AutostartRequest): AutostartPlan {
  const label = `com.spicyspec.${slug(req.projectName)}`;
  const plist = join(req.homeDir, 'Library', 'LaunchAgents', `${label}.plist`);
  const domain = `gui/${req.uid ?? 0}`;
  return {
    kind: 'launchd',
    unitName: label,
    requiresTool: 'launchctl',
    logDir: supervisorLogDir(req.stateDir),
    files: [{ path: plist, content: launchdPlist(req) }],
    // bootstrap refuses a label that is already loaded, so the update path is bootout first.
    install: [
      { bin: 'launchctl', args: ['bootout', `${domain}/${label}`], label: 'unload any previous version', optional: true },
      { bin: 'launchctl', args: ['bootstrap', domain, plist], label: 'load the agent' },
      { bin: 'launchctl', args: ['enable', `${domain}/${label}`], label: 'enable the agent' },
    ],
    uninstall: [{ bin: 'launchctl', args: ['bootout', `${domain}/${label}`], label: 'unload the agent', optional: true }],
    verify: [`launchctl print ${domain}/${label}`],
    notes: [
      'a LaunchAgent, so no sudo — it loads when you log in and repeats on the interval',
      `output is appended to ${join(supervisorLogDir(req.stateDir), 'supervisor.log')}`,
    ],
    needsElevation: false,
  };
}

export function planAutostart(req: AutostartRequest): AutostartPlan {
  const platform = req.platform ?? process.platform;
  if (platform === 'win32') return windowsPlan(req);
  if (platform === 'darwin') return launchdPlan(req);
  return systemdPlan(req);
}

export interface ApplyResult {
  readonly written: readonly string[];
  readonly ran: readonly string[];
  /** the install/uninstall tool is not on PATH — files are still written, commands printed */
  readonly toolMissing: boolean;
  readonly failures: readonly string[];
}

async function toolExists(bin: string): Promise<boolean> {
  try {
    // `where` / `which` are the only probes that answer for a bare name on PATH; spawning
    // the tool itself cannot distinguish "missing" from "bad arguments".
    const probe = process.platform === 'win32' ? 'where' : 'which';
    await run(probe, [bin], { windowsHide: true });
    return true;
  } catch {
    return false;
  }
}

/** Writes the plan's files, then runs its vectors. Never throws for an `optional` vector. */
export async function applyAutostart(plan: AutostartPlan, mode: 'install' | 'uninstall'): Promise<ApplyResult> {
  const written: string[] = [];
  const ran: string[] = [];
  const failures: string[] = [];

  if (mode === 'install') {
    for (const file of plan.files) {
      await mkdir(dirname(file.path), { recursive: true });
      await writeFile(file.path, file.content, 'utf8');
      if (file.executable) await chmod(file.path, 0o755);
      written.push(file.path);
    }
    await mkdir(plan.logDir, { recursive: true });
    written.push(plan.logDir);
  }

  if (!(await toolExists(plan.requiresTool))) {
    return { written, ran, toolMissing: true, failures };
  }

  for (const vector of mode === 'install' ? plan.install : plan.uninstall) {
    try {
      await run(vector.bin, [...vector.args], { windowsHide: true });
      ran.push(`${vector.bin} ${vector.args.join(' ')}`);
    } catch (err) {
      if (vector.optional) continue;
      failures.push(`${vector.label}: ${String((err as Error).message).split('\n')[0]}`);
    }
  }
  return { written, ran, toolMissing: false, failures };
}

/** Human-readable transcript — what happened, and the one line that proves it. */
export function describeAutostart(plan: AutostartPlan, result: ApplyResult, mode: 'install' | 'uninstall'): string[] {
  const out: string[] = [];
  for (const f of result.written) out.push(`wrote ${f}`);
  if (result.toolMissing) {
    out.push(`${plan.requiresTool} is not on PATH — nothing was registered. Run these yourself:`);
    for (const v of mode === 'install' ? plan.install : plan.uninstall) {
      out.push(`  ${v.bin} ${v.args.join(' ')}    # ${v.label}`);
    }
    return out;
  }
  for (const line of result.ran) out.push(`ran ${line}`);
  for (const f of result.failures) out.push(`FAILED ${f}`);
  if (mode === 'uninstall') {
    out.push(`removed ${plan.unitName}`);
    return out;
  }
  if (!result.failures.length) out.push(`installed ${plan.unitName} (${plan.kind})`);
  for (const n of plan.notes) out.push(`note: ${n}`);
  out.push('verify it:');
  for (const v of plan.verify) out.push(`  ${v}`);
  return out;
}
